os: linux
dist: xenial
language: ruby
cache:
  - bundler
install: true # skip bundle install
notifications:
  email: false

jobs:
  include:
    - env: TRAVIS_JOB=test
      rvm: 2.5.8

script: bash ./script/travis.sh
